version: 2
jobs:
  prepare:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ./bin/prepare
      - run: docker build .
workflows:
  version: 2
  build_and_test:
  jobs:
    - build
#    - test
