version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ./bin/prepare
      - run: docker build .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              ${TEST_FILES}
      - store_test_results:
          path: /tmp/test-results
  test:
    machine:
      enabled: true
    steps:
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              ${TEST_FILES}
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /[0-9]+.[0-9]+.[0-9]+/
                - /feature.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /[0-9]+.[0-9]+.[0-9]+/
                - /feature.*/


