version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ./bin/prepare
      - run: docker build .
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Test will happen here."
workflows:
  version: 2
  build_and_test:
  jobs:
    - build
#    - test
