version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /[0-9]+.[0-9]+.[0-9]+/
        - /feature.*/
    docker:
      - image: ruby:2.3.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install JQ to container
          command: |
            apt-get update && apt-get install jq
      - run:
          name: Prepare Bulild
          command: |
            ./bin/prepare
      - run:
          name: Build Image
          command: |
            docker build .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              ${TEST_FILES}
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Create version-branch if needed.
          command: |
            ./bin/createBranchIfNeeded


#workflows:
#  version: 2
#  nightly:
#    triggers:
#      - schedule:
#          cron: "1 2 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build
